# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterGuardMemoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='/rginfo/oper/celebrate/media/celebrate_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='registerguardmemory',
            name='image',
        ),
        migrations.AddField(
            model_name='registerguardmemoryimage',
            name='registerguardmemory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.RegisterGuardMemory'),
        ),
    ]
