# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170118_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerguardmemory',
            name='text',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
